server:
  port: 9090
  servlet:
    context-path: /v1/chapter-four

spring:
  application:
    name: chapter-four

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: root
    password: secret
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
      pool-name: connection-pool-chapter-four
      connection-test-query: select 1

  jpa:
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        format_sql: true
        generate_statistics: true
        show_sql: true
      jakarta:
        persistence:
          sharedCache:
            mode: NONE

  threads:
    virtual:
      enabled: true


logging:
  level:
    web: debug
    java: debug
    jakarta: debug
